eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
    prefer-ip-address: true
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  application:
    name: parking-lot-service
  main:
    allow-bean-definition-overriding: 'true'
  datasource:
    password: abc123
    username: root
    url: jdbc:mysql://localhost:3306/parking_lot_management
server:
  port: '8081'